[tool.black]
line-length = 100

[tool.pylint.messages_control]
max-line-length = 100
disable = [
  "missing-docstring",
  "unused-argument",
  "no-value-for-parameter",
  "no-member",
  "no-else-return",
  "line-too-long",
  "fixme",
  "protected-access",
  "too-few-public-methods",
  "too-many-statements",
  "trailing-whitespace",
  "too-many-locals",
  "too-many-branches",
  "too-many-nested-blocks",
  "redundant-keyword-arg",
  "consider-using-f-string",
  "protected-access",
  "unspecified-encoding",
  "consider-using-with",

  # We should clean up the code then remove these.
  "missing-class-docstring",
  "logging-fstring-interpolation",
  "f-string-without-interpolation",
  "missing-function-docstring",
  "broad-exception-caught",
  "too-many-instance-attributes",
  "trailing-whitespace",
  "trailing-newlines",
  "attribute-defined-outside-init",
  "unused-import",
  "multiple-statements",
]

[tool.pylint.format]
max-line-length = 100

[tool.isort]
line_length = 100
profile = "black"

[tool.flake8]
max-line-length = 100
